INSERT INTO PLAYER (ID, FIRST_NAME, LAST_NAME, CODE) VALUES (1001,'Denice', 'Howell', 'DH1001');

INSERT INTO PLAYER (ID, FIRST_NAME, LAST_NAME, CODE) VALUES (1002,'John', 'Gylock', 'JG1002');


INSERT INTO ACCOUNT (ID, BALANCE, NAME, PLAYER_ID) VALUES (101, 0.0, 'CURRENT', 1001);

INSERT INTO ACCOUNT (ID, BALANCE, NAME, PLAYER_ID) VALUES (102, 0.0, 'CURRENT', 1002);